CREATE DATABASE comatch_test WITH OWNER postgres ENCODING 'UTF8';;
GRANT ALL PRIVILEGES ON DATABASE comatch_test TO postgres;
CREATE TABLE  IF NOT EXISTS weather (date DATE PRIMARY KEY, year INTEGER NOT NULL,month INTEGER NOT NULL,tavg FLOAT,tmin FLOAT,tmax FLOAT,prcp  FLOAT,snow INTEGER,wdir INTEGER,wspd FLOAT,wpgt FLOAT,pres FLOAT,tsun INTEGER);